# Generated by Django 5.2.17 on 2026-09-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_probability', models.FloatField()),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('REVIEW', 'Review'), ('BLOCK', 'Block')], max_length=10)),
                ('model_version', models.CharField(default='RandomForest-v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_prediction', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='RuleViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('HIGH', 'High Severity')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_violations', to='transactions.transaction')),
            ],
        ),
    ]
