# Generated by Django 5.2.17 on 2026-09-14 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=50, unique=True)),
                ('merchant_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Retail', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default='Delhi', max_length=100)),
                ('device_id', models.CharField(default='DEV_DEFAULT_001', max_length=100)),
                ('is_new_device', models.BooleanField(default=False)),
                ('recent_transaction_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ALLOWED', 'Allowed'), ('REVIEW', 'Under Review'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.accountprofile')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.merchant')),
            ],
        ),
    ]
