# Generated by Django 5.2.17 on 2026-09-14 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_age_days', models.IntegerField(default=30)),
                ('average_transaction_amount', models.DecimalField(decimal_places=2, default=2500.0, max_digits=12)),
                ('usual_location', models.CharField(default='Delhi', max_length=100)),
                ('usual_device_id', models.CharField(default='DEV_DEFAULT_001', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
